(function(g){var window=this;var $8=function(a,b){var c=a.getAttribute(b);if(null!=c)return(0,window.parseFloat)(c)},a9=function(a){var b=1+.25*(a.Og||0);
if(0==a.offset||2==a.offset)b*=.8;return b},b9=function(a){if(!kxa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(lxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},c9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return g.Ou.test(c),c},d9=function(a,b){var c=$8(a,b);
if(void 0!=c)return c},e9=function(a,b){var c={};
if(null!=b.Od||b.background){var d=null!=b.Od?b.Od:a.g.Ya.Od,e=b9(b.background?b.background:a.g.Ya.background);c.background="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.U/8+"px")}if(null!=b.Og||null!=b.offset)c["font-size"]=a.$*a9(b)+"px";d=1;if(b.color||null!=b.Rf)e=b9(b.color||a.g.Ya.color),d=null==b.Rf?a.g.Ya.Rf:b.Rf,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;if(null!=b.cf&&0!=b.cf){e="rgba(34, 34, 34, "+d+")";d="rgba(204, 204, 204, "+
d+")";b.Zq&&(d=e=b.Zq);var f;switch(b.cf){case 4:f="2px 2px 3px "+e+", 2px 2px 4px "+e+", 2px 2px 5px "+e;break;case 1:f="1px 1px "+e+", 2px 2px "+e+", 3px 3px "+e;break;case 2:f="1px 1px "+d+", 0 1px "+d+", -1px -1px "+e+", 0 -1px "+e;break;case 3:f="0 0 4px "+e+", 0 0 4px "+e+", 0 0 4px "+e+", 0 0 4px "+e}c["text-shadow"]=f}f="";switch(b.fontFamily){case 1:f='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:f='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';
break;case 3:f='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:f='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:f='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:f=g.Mh()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:f='Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}f&&
(c["font-family"]=f);f=b.offset;null==f&&(f=a.g.Ya.offset);switch(f){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.In&&(c["font-style"]="italic");b.so&&(c["text-decoration"]="underline");b.an&&(c.visibility="hidden");return c},f9=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},g9=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.wa(c,a.Nv[d]);d=d9(b,"ap");null!=d&&(c.gg=d);d=$8(b,"cc");null!=d&&(c.jr=d);d=$8(b,"ah");null!=d&&(c.jh=d);d=$8(b,"rc");null!=d&&(c.Qi=d);d=$8(b,"av");null!=d&&(c.Bh=d);return c},h9=function(a,b,c){var d={},e=c.getAttribute("ws");
g.wa(d,e?b.Ov[e]:a.o);a=d9(c,"mh");null!=a&&(d.Kn=a);a=d9(c,"ju");null!=a&&(d.textAlign=a);a=d9(c,"pd");null!=a&&(d.Ah=a);a=c9(c,"wfc");null!=a&&(d.windowColor=a);c=$8(c,"wfo");void 0!=c&&(d.Fh=c/255);return d},i9=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.In=!0;break;case "u":k.so=!0;break;case "font":var m=f.getAttribute("color");g.Ou.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new g.Gu(a,b,c,d,n.nodeValue,e||0<m,g.Qb(k)?void 0:k));else{var r={};g.wa(r,k);i9(a,b,c,d,e||0<m,n,r,l)}}},mxa=function(){this.o=[];
this.b=[];this.g=-1},j9=function(a,b,c){a.G=a.G||!!c;
var d={};g.wa(d,a.g.Ya);g.wa(d,c||b.g);g.wa(d,a.oa.Ya);var e=a.D[0],f;if(e&&d.background==e.background&&d.Od==e.Od&&!!d.an==!!e.an&&d.cf==e.cf){for(c=0;c<a.D.length;c++)if(f9(d,a.D[c])){f=a.F[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.Me("SPAN");g.xl(f,e9(a,c));a.F[0].appendChild(f);c=1}a.F.length=c;a.D.length=c}else a.F.length=0,a.D.length=0,f=g.Me("SPAN"),g.xl(f,e9(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Se(a.C),f.appendChild(a.C));e=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.B.length||!b.C){if(0<c||0!=a.B.length){var m=g.Me("BR");f.appendChild(m)}f.appendChild(g.Ne("\u00a0"));a.C=g.Ne("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Ne(l):l,m))}a.D.push(d);a.F.push(f);a.B.push(b)},k9=function(a){if(a.o.captionTracks.length){var b=a.b.ij().Tq;
if(2==b||3==b)return!0}return 1==a.V.oa||1==a.o.yq||"alwayson"==a.o.De("yt:cc")?!0:2==a.V.oa&&(b=g.Ru(a,"module-enabled"),null!=b)?!!b:"on"==a.o.De("yt:cc")},l9=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},m9=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.In=!0;break;case "u":l.so=!0}for(var n=0;n<k.childNodes.length;n++){var r=k.childNodes[n];if(3==r.nodeType)r=new g.Gu(b,c,d,e.id,r.nodeValue,f||0<n,g.Qb(l)?void 0:l),m.push(r),e!=a.o&&e.Uh.push(r);else{var u={};g.wa(u,l);m9(a,b,c,d,e,!0,r,u,m)}}},n9=function(a,b,c,d){var e={};
g.wa(e,g9(b,c));g.wa(e,h9(a,b,c));d?(b="_"+g.Iu++,f9(e,a.o)&&(e=a.o)):b=c.getAttribute("id")||"0";a=$8(c,"t");c=$8(c,"d")||0x8000000000000;return new g.Hu(a,c,0,b,e)},o9=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},p9=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.cp("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");i9(d,e,k,b,f,a.firstChild,{},c)},q9=function(){this.g=[];
this.b=[]},r9=function(a){if(!a.H){var b=g.Me("SPAN");
g.xl(b,e9(a,a.g.Ya));a.A.appendChild(b);b.appendChild(g.Ne("M"));var c=b.offsetHeight,d=g.Me("BR");b.appendChild(d);b.appendChild(g.Ne("M"));a.H=b.offsetHeight-c;a.A.removeChild(b)}return a.H},s9=function(){this.xa=[]},t9=function(a){this.Rs=!!a;
this.b=new mxa;this.B=[]},u9=function(a,b){g.Ya(b,(0,g.w)(a.H,a))||b.push(a)},w9=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];
g.v(d.text)&&(b+=d.text.split("\n").length-1,d.C||0==c||b++)}return b},y9=function(a,b,c,d,e,f){this.B=[];
this.G=!1;this.o=a;this.D=[];this.F=[];this.wa=e;this.ra=f;this.C=null;this.N=.96*e;this.ka=.96*f;this.g={};g.wa(this.g,b);g.wa(this.g,this.o.params);g.wa(this.g,c);e={};g.wa(e,b.Ya);this.o.params.Ya&&g.wa(e,this.o.params.Ya);g.wa(e,c.Ya);this.g.Ya=e;this.oa=c;g.R.call(this,{J:"div",X:"caption-window",W:{id:"caption-window-"+a.id,dir:1==this.g.Ah?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:this.g.lang},P:[{J:"span",X:"captions-text"}]});this.A=this.sa["captions-text"];this.ga=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.$=d/360*16;this.type=0;this.U=this.$*a9(e);a=new g.xu(this.element,!0);g.K(this,a);a.subscribe("dragstart",this.eL,this);a.subscribe("dragmove",this.dL,this);a.subscribe("dragend",this.cL,this);this.ca=this.ba=0;a="";this.g.Fh&&(a=b9(this.g.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.g.Fh+")");b={"background-color":a,display:!1===this.g.isVisible?"none":"","text-align":nxa[this.g.textAlign]};this.ga&&(b["border-radius"]=a?this.U/8+
"px":"");g.xl(this.element,b);switch(this.g.gg){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},z9=function(a){return g.Ku(a)?!a.o.g:a.o.captionTracks.length&&a.b.ij().Vj?!0:k9(a)},A9=function(a,b){q9.call(this);
this.o=g.Ju({Kn:0});this.b.push(this.o);for(var c=a.split(oxa),d=1;d<c.length;d++){var e=c[d],f=b;if(""!=e&&!pxa.test(e)){var k=g.n8.exec(e);if(k&&3<=k.length){var l=l9(k[1]),k=l9(k[2])-l,e=e.substring(g.n8.lastIndex);g.n8.lastIndex=0;var f=l+f,l=k,m=e,k={},n=this.o,e=5;if(0>m.indexOf("<"))this.g.push(new g.Gu(f,l,e,n.id,m,!1,g.Qb(k)?void 0:k));else{m=m.split(qxa);1!=m.length&&(e=6,n="_"+rxa++,n=new g.Hu(f,l,e,n,{}),this.b.push(n));for(var r=f,u=0;u<m.length;u++){var x=m[u];if(0==u%2){var z=g.cp("<html>"+
x+"</html>"),B;z.getElementsByTagName("parsererror").length?(B=z.createElement("span"),B.appendChild(z.createTextNode(x))):B=z.firstChild;m9(this,r,l-(r-f),e,n,0<u,B,k,this.g)}else r=l9(x)}}}g.n8.lastIndex=0}}},B9=function(a,b){q9.call(this);
a.firstChild.getAttribute("format");this.o=b;for(var c={Ik:{},Nv:{},Ov:{}},d,e,f=a.firstChild.childNodes,k=0;k<f.length;k++){var l=f[k];switch(l.tagName){case "head":d=l;break;case "body":e=l}}if(d)for(d=d.childNodes,f=0;f<d.length;f++){var m=d[f];switch(m.tagName){case "pen":var l=m.getAttribute("id"),k=c.Ik,n=c,r=m,m={},u=r.getAttribute("p");u&&g.wa(m,n.Ik[u]);n=o9(r,"b");null!=n&&(m.bold=n);n=o9(r,"i");null!=n&&(m.In=n);n=o9(r,"u");null!=n&&(m.so=n);n=d9(r,"et");null!=n&&(m.cf=n);n=d9(r,"of");
null!=n&&(m.offset=n);n=c9(r,"bc");null!=n&&(m.background=n);n=c9(r,"ec");null!=n&&(m.Zq=n);n=c9(r,"fc");null!=n&&(m.color=n);n=d9(r,"fs");void 0!=n&&0!=n&&(m.fontFamily=n);n=$8(r,"sz");void 0!=n&&(m.Og=n/100-1);n=$8(r,"bo");void 0!=n&&(m.Od=n/255);r=$8(r,"fo");void 0!=r&&(m.Rf=r/255);k[l]=m;break;case "ws":k=m.getAttribute("id");c.Ov[k]=h9(this,c,m);break;case "wp":k=m.getAttribute("id"),c.Nv[k]=g9(c,m)}}if(e)for(d={},e=e.childNodes,f=void 0,k=0;k<e.length;k++)switch(l=e[k],l.tagName){case "w":m=
n9(this,c,l);if(l=d[m.id])l.end=m.start;d[m.id]=m;this.b.push(m);break;case "p":var m=c,x=l,z=f,r=[],n=$8(x,"t")||0,u=$8(x,"d")||0,B=x.getAttribute("w")||"0",G=!!o9(x,"a");z&&"\n"==z.text&&!G&&(G=!0);for(var z=G?6:5,J=m.Ik[x.getAttribute("p")],x=x.childNodes,O=0;O<x.length;O++){var Ra=x[O];0<O&&(G=!0);if("s"==Ra.tagName)var bb=Ra,Ra=n,rb=u,$c=B,hp=G,Ws=z,Xs=bb.textContent?bb.textContent:"",Ys=m.Ik[bb.getAttribute("p")],bb=$8(bb,"t")||0,Ra=new g.Gu(Ra+bb,rb-bb,Ws,$c,Xs,hp,Ys);else Ra=new g.Gu(n,u,
z,B,Ra.textContent||"",G,J);r.push(Ra)}if(0<r.length)for(f=r[r.length-1],m=d[r[0].o],m||(m=n9(this,c,l,!0),this.b.push(m)),l=0;l<r.length;l++)n=r[l],r[l].o=m.id,m.Uh.push(n),this.g.push(n)}},C9=function(a){q9.call(this);
this.o={};var b=g.Ju();this.o[b.id]=b;this.b.push(b);for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.o[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=g.Ju());var k={};f&&(g.wa(k,f.params),f=f.params.Ya)&&
(k.Ya={},g.wa(k.Ya,f));e.getAttribute("rc")&&(k.Qi=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.jr=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.gg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.jh=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Bh=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));e.getAttribute("ju")&&(k.textAlign=
(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Ah=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Ah=0));e.getAttribute("bc")&&(k.Ya||(k.Ya={}),k.Ya.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Ya||(k.Ya={}),k.Ya.Od=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Ya||(k.Ya={}),k.Ya.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.KI=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new g.Hu(c,f,0,e,k)}else c=null}this.o[d]=c;this.b.push(c);break;case "text":for(d=this.g.length,p9(a,b.id,this.g);d<this.g.length;d++)c=this.g[d],(k=this.o[c.o])&&k.Uh.push(c)}a=a.nextSibling}0==this.b.length&&this.b.push(g.Ju())},D9=function(a,b){q9.call(this);
var c=g.Ju(b);this.b.push(c);for(var d=a.firstChild.childNodes,e=0,f=d.length;e<f;e++)p9(d[e],c.id,this.g)},E9=function(a,b,c,d){t9.call(this,d);
c||(c=g.Ah(a).hl||"",c=c.split("_").join("-"));this.o=g.Ch(a,{hl:c});this.A=b;this.C={};this.g=null},F9=function(a,b,c,d,e,f){y9.call(this,a,b,c,d,e,f);
g.M(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.S=0;this.fa=window.NaN;this.L=null;this.K=new g.Ed(this.pa,433,this);g.K(this,this.K)},G9=function(a,b,c,d,e,f){y9.call(this,a,b,c,d,e,f);
this.type=1},H9=function(a,b){t9.call(this);
this.o=a;this.Z=b;this.g=null},I9=function(a,b,c,d){g.I.call(this);
this.G=b;this.B=new s9;this.b=null;this.F=d;this.g=this.o=null;this.K=c;this.C=new g.Ed(this.D,1E3,this);g.K(this,this.C);b.addEventListener("seekto",this.A,this);this.A(b.getCurrentTime());this.D()},J9=function(a){t9.call(this,a.Qc);
this.g=null;this.A=void 0;this.o=null;this.B=a.captionTranslationLanguages},sxa=function(a,b){var c=g.Xa(a.b,(0,g.w)(b.H,b));
-1!=c&&(a.g=c)},K9=function(a,b){switch(b.A){case "asr":u9(b,a.o);
break;default:if(b.isDefault||0>a.g)a.g=a.b.length;u9(b,a.b)}},L9=function(a){return a.b?a.b.languageCode:a.g},txa=function(a){for(var b in a)delete a[b]},M9=function(a,b){return g.aa[a]=b},N9=function(a){g.km.call(this,a);
g.vu();this.V=g.T(a);this.o=a.getVideoData();this.$=g.$t(a);this.Z=a;var b=null,c=g.vi("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wi(c));this.S=b;this.B={Ya:{}};this.C={Ya:{}};this.G=[];this.F={};this.L={};this.K=!1;this.fa="1"==this.o.B.cc_auto_caps||"1"==this.V.G.cc_auto_caps;c=b=this.A=this.g=this.D=this.H=this.aa=null;g.Ku(this)||(b=new g.Ed(this.Bv,0,this),g.K(this,b),c=new g.Ed(this.gI,2E3,this),g.K(this,c));this.U=b;this.ca=c;this.N=new g.pm(this);g.K(this,this.N);g.Ku(this)||
this.N.T(a,"resize",this.uo);this.N.T(a,"onPlaybackAudioChange",this.cE);this.N.T(a,"crn_captions",this.LK,this);this.N.T(a,"crx_captions",this.MK,this);g.Qu(this,g.Ru(this,"display-settings")||{});z9(this)&&this.load()},kxa=/^#(?:[0-9a-f]{3}){1,2}$/i,lxa=/#(.)(.)(.)/,nxa=["left",
"right","center"],qxa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,oxa=/(?:\r\n|\r|\n){2,}/,pxa=/^NOTE/,rxa=0,uxa={an:!0};s9.prototype.contains=function(a){a=g.tb(this.xa,a);return 0<=a||0>a&&1==(-a-1)%2};
s9.prototype.length=function(){return this.xa.length/2};
g.A(t9,g.I);t9.prototype.Or=function(a){var b=this.b.g,c=g.Bu(this.b,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
t9.prototype.Zj=function(){return null};
t9.prototype.R=function(){t9.M.R.call(this);this.ee()};
g.A(y9,g.R);g.h=y9.prototype;g.h.eL=function(a,b){var c=g.Ll(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.M(this.element,"ytp-dragging")};
g.h.dL=function(a,b){var c=g.Ol(this.element),d=a-this.ba-.02*this.wa,e=b-this.ca-.02*this.ra,f=(d+c.width/2)/this.N*3,f=Math.floor(g.oe(f,0,2)),k=(e+c.height/2)/this.ka*3,k=Math.floor(g.oe(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.N,d=100*g.oe(d,0,1),c=(e+k/2*c.height)/this.ka,c=100*g.oe(c,0,1);this.o.params.gg=l;this.o.params.Bh=c;this.o.params.jh=d;this.g.gg=l;this.g.Bh=c;this.g.jh=d;this.xh(this.B)};
g.h.cL=function(){g.Ld(this.element,"ytp-dragging")};
g.h.Qb=function(){return this.type};
g.h.xh=function(a){var b=Math.min(this.Qr(),this.N),c=this.Pr();g.xl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.$l(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.g.jh+2,e=this.g.gg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.g.Bh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.xl(this.element,a)};
g.h.$l=function(a){for(var b=0;b<a.length&&a[b]==this.B[b];b++);if(this.G||this.B.length>b)b=0,this.G=!1,this.B=[],this.D=[],this.F=[],this.C=null,g.Qe(this.A);for(;b<a.length;b++)j9(this,a[b])};
g.h.Qr=function(){return 0};
g.h.Pr=function(){return 0};
g.h.toString=function(){return y9.M.toString.call(this)};
g.A(A9,q9);g.A(B9,q9);g.A(C9,q9);g.A(D9,q9);g.A(E9,t9);g.h=E9.prototype;g.h.kh=g.ba(3);g.h.lh=g.ba(9);g.h.Cf=g.ba(6);g.h.ee=function(){this.g&&this.g.abort()};
g.h.R=function(){this.ee();E9.M.R.call(this)};
g.A(F9,y9);F9.prototype.pa=function(){g.Ld(this.element,"ytp-rollup-mode");var a=this.L;this.L=null;this.xh(a)};
F9.prototype.Qr=function(){var a=this.o.params.jr;if(!this.S&&a){var b=g.Me("SPAN");g.$e(b,"\u00a0"+(0,g.Ia)("\u2014",a)+"\u00a0");g.xl(b,e9(this,this.g.Ya));this.A.appendChild(b);this.S=b.offsetWidth;this.A.removeChild(b)}return this.S};
F9.prototype.Pr=function(){return this.o.params.Qi*r9(this)};
F9.prototype.xh=function(a){if(r9(this)){for(var b=0,c=0;b<this.B.length&&c<a.length;b++)this.B[b]==a[c]&&c++;var d=w9(a),e=!1,b=0;if(0<c&&c<a.length){var c=this.B.concat(a.slice(c)),f=w9(c)-d;0<f&&(this.L=a,a=c,b-=f,e=!0)}d<this.o.params.Qi&&(b+=this.o.params.Qi-d);e&&!this.K.isActive()&&(g.M(this.element,"ytp-rollup-mode"),this.K.start());b!=this.fa&&(d="",b&&(d="translateY("+Math.ceil(b*r9(this))+"px)"),g.xl(this.A,"transform",d),this.fa=b);F9.M.xh.call(this,a)}else F9.M.xh.call(this,a)};
g.A(G9,y9);G9.prototype.$l=function(a){var b=this.o.Uh;G9.M.$l.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.g==c?f=d:(f={},g.wa(f,e.g),g.wa(f,uxa),c=e.g,d=f);j9(this,e,f)}};
g.A(H9,t9);g.h=H9.prototype;g.h.kh=g.ba(4);g.h.lh=g.ba(10);g.h.ee=function(){this.g&&(this.g.dispose(),this.g=null)};
g.h.Cf=g.ba(7);g.h.R=function(){this.ee();H9.M.R.call(this)};
g.A(I9,g.I);I9.prototype.R=function(){I9.M.R.call(this);this.G.removeEventListener("seekto",this.A,this);this.g&&this.g.abort()};
I9.prototype.A=function(a){this.b=g.Wa(this.K.pi(a).b)};
I9.prototype.D=function(){this.isDisposed();var a;if(a=null!==this.b)a=this.b,a=a.b.Xo(a);if(a&&!this.g&&!(this.b&&30<this.b.startTime-this.G.getCurrentTime())){a=this.b;a=a.b.xl(a);if(!this.B.contains(a.b[0].o)){var b=g.Ow(g.Xw(a));this.g=g.ii(b,{format:"RAW",Zc:(0,g.w)(this.H,this),withCredentials:!0});this.o=a;var b=this.B,c=this.o.b[0].o,d=g.tb(b.xa,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.xa[d-1]&&d<b.xa.length&&1==b.xa[d]-c?(g.fb(b.xa,d),g.fb(b.xa,d-1)):0<d&&1==c-b.xa[d-1]?b.xa[d-1]=c:
d<b.xa.length&&1==b.xa[d]-c?b.xa[d]=c:(g.ob(b.xa,d,0,c),g.ob(b.xa,d+1,0,c)))}this.b=g.Wa(a.b)}this.C.start()};
I9.prototype.H=function(a){this.isDisposed();null==a.responseText||400<=a.status||null===this.F||this.F(a.responseText,1E3*this.o.b[0].startTime);this.g=this.o=null};
g.A(J9,t9);g.h=J9.prototype;g.h.kh=g.ba(5);g.h.lh=g.ba(11);g.h.Cf=g.ba(8);g.h.Zj=function(){return this.g?this.g.Vj:null};
g.h.Or=function(){return this.g?this.g.xm:null};
g.h.ee=function(){this.o&&this.o.abort()};
g.h.R=function(){this.ee();J9.M.R.call(this)};
var vxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;J9.prototype.lh=M9(11,function(a,b,c,d){this.A=c;if(this.g=d||null)for(b=0;b<this.g.captionTracks.length;b++)K9(this.b,this.g.captionTracks[b]);a()});
H9.prototype.lh=M9(10,function(a){K9(this.b,new g.Dn({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()});
E9.prototype.lh=M9(9,function(a,b,c){var d=this.o;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Rs&&(b.asrs=1);d=g.Ch(d,b);b=(0,g.w)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.b,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),r=c,u=e[m].getAttribute("lang_code"),x=e[m].getAttribute("lang_translated"),z=e[m].getAttribute("name"),B=e[m].getAttribute("kind"),G=e[m].getAttribute("id"),J="true"==e[m].getAttribute("lang_default"),
O="true"==e[m].getAttribute("cantran"),Ra=e[m].getAttribute("vss_id");K9(d,new g.Dn({formats:n,format:r,languageCode:u,languageName:x,name:z,kind:B,id:G,is_servable:!0,is_default:J,is_translateable:O,vss_id:Ra}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),u="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:r,is_default:u},this.C[l.languageCode]=l.languageName,this.B.push(new g.Cn(l))}a()},this);
this.ee();this.g=g.ii(d,{format:"RAW",Bb:b,withCredentials:!0})});
J9.prototype.Cf=M9(8,function(a){var b=a.G,c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.b&&(c.tlang=a.b.languageCode);return g.Ch(b,c)});
H9.prototype.Cf=M9(7,function(){return""});
E9.prototype.Cf=M9(6,function(a){var b=this.o,c={v:this.A,type:"track",lang:a.g,name:a.getName(),kind:a.A,fmt:a.o};a.b&&(c.tlang=L9(a));return b=g.Ch(b,c)});
J9.prototype.kh=M9(5,function(a,b){this.isDisposed();var c=this.Cf(a),d=(0,g.w)(function(c){this.o=null;b(c.responseText,a)},this);
this.ee();this.o=g.ii(c,{format:"RAW",Bb:d,withCredentials:!0});this.g&&this.g.Vj!=a&&(this.g.xm=a)});
H9.prototype.kh=M9(4,function(a,b){this.ee();var c=this.o.b[a.g];c&&(this.g=new I9(0,this.Z,c,function(c,e){b(c,a,e)}))});
E9.prototype.kh=M9(3,function(a,b){this.isDisposed();var c=this.Cf(a),d=(0,g.w)(function(c){this.g=null;b(c.responseText,a)},this);
this.ee();this.g=g.ii(c,{format:"RAW",Bb:d,withCredentials:!0});sxa(this.b,a)});
g.Pn.prototype.Dj=M9(2,function(a){for(var b=0;b<a.length;b++)this.b.appendChild(a[b])});
g.t3.prototype.Dj=M9(1,function(){});
g.Dn.prototype.H=M9(0,function(a){return a?this.toString()==a.toString():!1});
g.A(N9,g.km);g.h=N9.prototype;g.h.R=function(){g.Ku(this)||g.Wu(this,!1);N9.M.R.call(this)};
g.h.load=function(a){N9.M.load.call(this);if(this.g||a)this.A?(a?this.tu(a,this.A):3!=this.b.Xa()&&this.g.kh(this.A,(0,g.w)(this.tu,this)),this.b.Ba("captionschanged",g.Fn(this.A))):this.b.Ba("onCaptionsTrackListChanged");else{var b;this.o.g?b=new H9(this.o.b,this.b):(a=(a=this.o.wq||this.V.sc||this.o.De("yt:cc_default_lang")||this.V.Ma)&&a.split("_").join("-"),this.o.captionTracks.length?b=new J9(this.o):b=new E9(this.o.xd,this.o.videoId,a,this.o.Qc));this.g=b;b.lh((0,g.w)(this.hH,this),!0,g.Ku(this)?
"vtt":void 0,this.b.ij())}};
g.h.unload=function(){if(g.Ku(this))for(var a=g.Be("track",void 0,this.$.g),b=0;b<a.length;b++)g.Se(a[b]);else g.Gd(this.ca),g.Di(this.b,"captions"),this.G=[],this.g&&this.g.ee(),this.D&&g.Bi(this.b,this.D),this.uo();N9.M.unload.call(this);(a=g.ov(this.b.app))&&g.TV(a);this.b.Ba("captionschanged",{})};
g.h.hH=function(){var a;if(this.K||k9(this))a=g.Lu(this,this.K);if(g.Ku(this))for(var b=g.Bu(this.g.b,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.En(d),srclang:L9(d),src:this.g.Cf(d)};d==a&&(e["default"]=1);this.Z.app.C.Dj([g.N("TRACK",e)])}else!this.A&&a&&g.Mu(this,a),this.b.Ba("onCaptionsTrackListChanged")};
g.h.tu=function(a,b,c){if(a){var d;d={};var e=L9(b);e&&(d.lang=e,vxa.test(e)&&(d.Ah=1));d="WEBVTT"==a.substring(0,6)?new A9(a,c||0):(a=g.cp(a))&&a.firstChild?"timedtext"==a.firstChild.tagName?3==(0,window.parseInt)(a.firstChild.getAttribute("format"),10)?new B9(a,d):new C9(a):new D9(a,d):new q9;a={trackName:b.getName(),trackKind:b.A,trackLangCode:L9(b)};b.b&&(a.fromLangCode=b.g);g.sr(this.b,"cc",a);this.A!=this.g.Zj()&&(!this.K||g.To(this.V)||g.Vo(this.V)||(g.Gd(this.ca),b=g.Ju({gg:0,jh:5,Bh:5,Qi:2,
textAlign:0,Ah:0,lang:"en"}),this.H=[b],a=g.P("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.aa||(c=new g.Nj(g.Mg()),g.K(this,c),this.aa=c.element),c=b.end-b.start,(e=g.En(this.A))&&this.H.push(new g.Gu(b.start,c,0,b.id,e)),this.H.push(new g.Gu(b.start,c,0,b.id,a[0]),new g.Gu(b.start,c,0,b.id,this.aa,!0),new g.Gu(b.start,c,0,b.id,a[1],!0)),g.Bi(this.b,this.H),this.ca.be()),(this.K||g.To(this.V))&&g.Pu(this,"module-enabled",!0),(b=g.ov(this.b.app))&&g.TV(b));g.Bi(this.b,d.b.concat(d.g));this.K=
!1}};
g.h.LK=function(a){this.G.push(a);this.U.be()};
g.h.MK=function(a){g.gb(this.G,a);this.U.be()};
g.h.XH=function(a){if(a instanceof g.Hu){var b=this.F[a.id];b&&b.o!=a&&(b.dispose(),delete this.F[a.id],b=null);if(!b){var b=this.F,c=a.id;a:{var d=this.$.Sa(),e=g.Zt(this.$,!0).height;switch(null!=a.params.Kn?a.params.Kn:a.params.KI?2:1<a.Uh.length?1:0){case 1:a=new G9(a,this.B,this.C,e,d.width,d.height);break a;case 2:a=new F9(a,this.B,this.C,e,d.width,d.height);break a;default:a=new y9(a,this.B,this.C,e,d.width,d.height)}}b[c]=a}}else b=a.o,this.L[b]||(this.L[b]=[]),this.L[b].push(a)};
g.h.gI=function(){g.Yu(this,this.H);this.H=null};
g.h.Bv=function(){this.U.stop();txa(this.L);this.G.sort(g.yi);(0,g.F)(this.G,this.XH,this);g.Fb(this.F,function(a,b){!this.L[b]||this.D&&-1==this.D.indexOf(a.o)?(a.dispose(),delete this.F[b]):(a.element.parentNode||g.ys(this.b,a.element,5),a.xh(this.L[b]))},this)};
g.h.uo=function(){!g.Ku(this)&&this.loaded&&(g.Fb(this.F,function(a,b){a.dispose();delete this.F[b]},this),this.Bv())};
g.h.Zf=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.V.ib&&a.push("stickyLoading","xmlTrack");return a};
g.h.cE=function(){this.o.captionTracks.length&&(this.loaded&&this.unload(),z9(this)&&this.load())};
window._exportCheck==g.ya&&g.la("ytmod.player.captions",N9,void 0);})(_yt_player);
